---
# tasks file for ansible-app_to_marathon
- name: "Launching app: {{ marathon_app.id }}"
  tags:
    - create
    - update
  uri: >
    url="{{ marathon_url }}/v2/apps/{{marathon_app.id}}"
    method=PUT
    body_format=json
    body='{{ marathon_app | to_json }}'
    status_code=200,201
  register: marathon_deployment

- name: "Waiting for app: {{ marathon_app.id }}"
  tags:
    - create
    - wait
  uri: >
    url="{{ marathon_url }}/v2/deployments"
    method=GET
    status_code=200
  register: marathon_deployments
  until: "{{ marathon_deployment.json.deploymentId not in marathon_deployments.json|map(attribute='id') }}"
  delay: 1
  retries: '{{ retries }}'
  when: marathon_wait_for_deployment

- name: "Restartnig app: {{marathon_app.id}}"
  tags:
    - restart
  uri: >
    url="{{ marathon_url }}/v2/apps/{{marathon_app.id}}/restart"
    method=POST
    status_code=200
  when: restart is defined

- name: "Destroying app: {{marathon_app.id}}"
  tags:
    - destroy
  uri: >
    url="{{ marathon_url }}/v2/apps/{{marathon_app.id}}"
    method=DELETE
    status_code=200
  when: destroy is defined

- name: "Scale app: {{marathon_app.id}}"
  tags:
    - scale
  uri: >
    url="{{ marathon_url }}/v2/apps/{{marathon_app.id}}"
    method=PUT
    body_format=json
    body='{"instances": {{scale_to}}}'
    status_code=200,201
  when: scale_to is defined
